### ISSUE TITLE
Titles don't show up for buttons in nib?

### ISSUE THREAD

**Issue by pepasflo** [dcordero/FocusTvButton#25]
For some reason, none of the titles show up on any buttons which live in a nib.

If I programmatically create the button, it works fine.

**Comment by dcordero** [comment]
Hi @pepasflo. 

This should be working fine. Did you check [the steps in README.md](https://github.com/dcordero/FocusTvButton#embedded-in-a-xib-or-storyboard-file) describing how to add FocusTvButton from nib or storyboards?

Could you check the example projects in this repo? you will find a [simple example App](https://github.com/dcordero/FocusTvButton/tree/master/Example/Swift) with two buttons.  One of the buttons is created programmatically and the other one defined in a nib. 

In this example, the title in both buttons seems to be working fine. 

Is there something different in your use case?

<img width="1066" alt="screen shot 2019-01-30 at 09 50 59" src="https://user-images.githubusercontent.com/2320840/51969396-95d3c200-2474-11e9-81bf-e1d081a2d9b6.png">

**Comment by pepasflo** [comment]
Ah, I had missed the step of setting the button type to "Custom"

![screen shot 2019-01-30 at 12 09 50 pm](https://user-images.githubusercontent.com/25310741/52002592-0df7b300-2488-11e9-8be6-04a419d25a30.jpg)

After doing that it works!

Sorry for not RTFMing closely enough 😁
