### ISSUE TITLE
Instance member 'layer' cannot be used on type 'GradientView'

### ISSUE THREAD

**Issue by Riya3189** [dcordero/FocusTvButton#26]
Facing this compilation issue after updating my pod to the latest version of FocusTvButton. 

.../Pods/FocusTvButton/FocusTvButton/Source/FocusTvButton.swift:300:16: Instance member 'layer' cannot be used on type 'GradientView'

**Comment by elonmaxhimself** [comment]
Sometimes the problem is that swift autocompletes "awakeFromNib" with "override class func awakeFromNib() {...}" but it supposed to be "override func awakeFromNib()"

**Comment by yusuf-keskin** [comment]
> Sometimes the problem is that swift autocompletes "awakeFromNib" with "override class func awakeFromNib() {...}" but it supposed to be "override func awakeFromNib()"

Thank you. It happened just as you said.
