### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by thejohnlima** [dcordero/FocusTvButton#33]
Hello there, 

Am I doing anything wrong or the latest version (`3.1.0`) can't be installed through cocoapods?
This the error I'm seeing:

<img width="1194" alt="Screenshot 2022-11-09 at 1 06 25 PM png" src="https://user-images.githubusercontent.com/12019206/200933094-45a75087-4881-4977-8b15-f7602c02d744.png">

**Comment by dcordero** [comment]
@thejohnlima Thanks for heads up.

I forgot to push the new version to CocoaPods trunk, it should be working now with: 

`pod install --repo-update`
