### ISSUE TITLE
Cannot close app with Menu button when FocusTvButton has focus

### ISSUE THREAD

**Issue by ruudruud** [dcordero/FocusTvButton#8]
My tvOS app is unable to close/hide the app when pressing the Menu button on the Apple TV remote when a FocusTvButton has focus. Is there a simple solution for this issue?

**Comment by dcordero** [comment]
This issue has been fixed and released as part of the [release 1.0.0](https://github.com/dcordero/FocusTvButton/releases/tag/1.0.0)


Thanks for reporting the issue @ruudruud
